apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastly-logging
  name: fastly-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastly-logging
  template:
    metadata:
      labels:
        app: fastly-logging
    spec:
      containers:
      - image: guyeise5/fastly-logging
        name: fastly-logger
        ports:
        - containerPort: 8080
