apiVersion: v2
name: squares-app
description: A demo application to show k8s rollout process

type: application

version: 1.0.0

appVersion: "1.0.0"

maintainers:
  - email: email@example.com
    name: Name
