{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.nameOverride | default (print .Release.Name "-fastly-logging") }}
spec:
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.nameOverride | default (print .Release.Name "-fastly-logging") }}
                port:
                  name: app
{{- end}}
