{{- if .Values.ngrok.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngrok-fastly-logging
  name: ngrok-fastly-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok-fastly-logging
  template:
    metadata:
      labels:
        app: ngrok-fastly-logging
    spec:
      containers:
      - image: {{ .Values.ngrok.image }}
        name: ngrok
        command: 
        - ngrok
        args: 
        - http
        - --region={{ .Values.ngrok.region }}
  {{- if .Values.ngrok.hostName}}
        - --hostname={{ .Values.ngrok.hostName }}
  {{- end}}
        - --log=stdout
        - http://fastly-logging
        env:
        - name: NGROK_AUTHTOKEN
          value: {{ .Values.ngrok.authToken | default ""}}
  {{- end}}