apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nameOverride | default (print .Release.Name "-fastly-logging") }}
  name: {{ .Values.nameOverride | default (print .Release.Name "-fastly-logging") }}
spec: 
  type: {{.Values.service.type}}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: app
    targetPort: 8080
    {{- if and (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end}}
  selector:
    app: {{ .Values.nameOverride | default (print .Release.Name "-fastly-logging") }}